# Generated by Django 5.2.4 on 2026-07-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter employee's full name.", max_length=150)),
                ('email', models.EmailField(help_text="Enter employee's email address.", max_length=254, unique=True)),
                ('phone', models.CharField(help_text="Enter employee's contact number.", max_length=20)),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('IT', 'Information Technology'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Sales', 'Sales')], default='IT', help_text="Select employee's department.", max_length=50)),
                ('designation', models.CharField(help_text='Enter job title / designation.', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text="Enter employee's monthly salary.", max_digits=10)),
                ('joining_date', models.DateField(help_text='Select date of joining.')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Current employment status.', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
